############################################################################
# app/bk7258_gdma_test/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = bk7258_gdma_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_272_BK7258_GDMA_TEST)

MAINSRC = bk7258_gdma_test_main.c

include $(APPDIR)/Application.mk
