############################################################################
# BK7258 platform API and register readback test
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = bk7258_platform_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_272_BK7258_PLATFORM_TEST)

MAINSRC = bk7258_platform_test_main.c

include $(APPDIR)/Application.mk
